version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - echo $READTHEDOCS_PROJECT
      - git clone -b dev https://github.com/griptape-ai/griptape.git
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
