version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - git clone -b $([ $READTHEDOCS_VERSION_NAME = "latest" ] && echo "main" || echo "dev") https://github.com/griptape-ai/griptape.git
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
