name: Read the Docs Dev Preview
on:
  pull_request_target:
    types:
      - opened
    paths:
      - "docs/**"
    branches:
      - 'dev'

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: dev-griptape-docs
          single-version: 'true'
