name: Read the Docs Build Dev1
on: push

permissions:
  pull-requests: write

jobs:
  readthedocs-build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: |
            curl --silent \
            --request POST \
            --header "Authorization: Token $READTHEDOCS_API_TOKEN" \
            --url "$READTHEDOCS_API_ENDPOINT/projects/$READTHEDOCS_PROJECT_SLUG/versions/$READTHEDOCS_VERSION/builds/"
        env:
          READTHEDOCS_VERSION: ${{ github.ref_name }}
          READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_API_TOKEN }}
          READTHEDOCS_API_ENDPOINT: ${{ secrets.READTHEDOCS_API_ENDPOINT }}
          READTHEDOCS_PROJECT_SLUG: ${{ secrets.READTHEDOCS_PROJECT_SLUG_DEV }}
