name: Read the Docs Build
on:
  push:
    branches: [ "main"]
    paths:
      - "docs/**"
  pull_request:
    branches: [ "main"]
    paths:
      - "docs/**"

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: griptape
          single-version: 'true'
  readthedocs-prod-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: |
            curl --request POST \
            --url "$READTHEDOCS_ENDPOINT_PROD/versions/$GITHUB_REF/builds/" \
            --header "Authorization: Token $READTHEDOCS_API_TOKEN"
        env:
          READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_API_TOKEN }}
          READTHEDOCS_ENDPOINT_PROD: ${{ secrets.READTHEDOCS_ENDPOINT_PROD }}
